# Generated by Django 2.1.2 on 2018-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Operador'), (3, 'Locatario'), (4, 'Proprietario'), (5, 'Outros')], default=5, max_length=2),
        ),
    ]
