# Generated by Django 2.1.2 on 2018-11-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_auto_20181112_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='tipo_locacao',
            field=models.IntegerField(choices=[(1, 'ALUGUEL-POR-TEMPORADA'), (2, 'ALUGUEL-COMERCIAL'), (3, 'ALUGUEL-RESIDENCIAL'), (4, 'VENDA')], default=3),
        ),
    ]
